### ISSUE TITLE
Creating an Observation fails

### ISSUE THREAD

**Issue by bausmeier** [liwoo/mini-fhir#2]
POSTing [one of the example Observations](https://www.hl7.org/fhir/observation-example.json.html) from the [vital signs profile](https://www.hl7.org/fhir/observation-vitalsigns.html#vitals-table) to `/fhir/Observation` returns a 422 status code with the message: '"system" is not allowed'.

**Comment by liwoo** [comment]
awesome... lemme look into this

**Comment by liwoo** [comment]
I believed I have resolved this issue and added a test case where the example Observation is successfully created. @bausmeier, please verify this before I mark the issue as closed

**Comment by bausmeier** [comment]
Thanks, this is working now :+1:
